name: Trigger Airtable API on Commit
on:
  push:
    branches:
      - main

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Send Commit Info to Airtable
        env:
          AIRTABLE_API_URL: https://api.airtable.com/v0/appca9wvd0Q5x2Gu2/Commits
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_SECRET }}
        run: |
          # Get code changes as plain text
          CODE_CHANGES=$(git diff HEAD^ HEAD)

          # Escape double quotes for JSON compatibility
          CODE_CHANGES_ESCAPED=$(echo "$CODE_CHANGES" | sed 's/"/\\"/g')

          # Get commit details with the escaped code changes
          COMMITS=$(git log -1 --pretty=format:'{ 
            "Commit Date":"%ad", 
            "Repository URL":"${{ github.server_url }}/${{ github.repository }}", 
            "Author Email":"%ae", 
            "Repository Name":"${{ github.repository }}", 
            "Commit Message":"%s", 
            "Github Username":"${{ github.actor }}", 
            "Code Committed":"'"$CODE_CHANGES_ESCAPED"'"
          }' --date=iso)

          BODY="{\"records\":[{\"fields\":$COMMITS}]}"

          curl -X POST $AIRTABLE_API_URL \
            -H "Authorization: Bearer $AIRTABLE_API_KEY" \
            -H "Content-Type: application/json" \
            --data "$BODY"
