name: Trigger Airtable API on Commit
on:
  push:
    branches:
      - main

jobs:
  trigger-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Send Commit Info to Airtable
        env:
          AIRTABLE_API_URL: https://api.airtable.com/v0/appca9wvd0Q5x2Gu2/Commits
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_SECRET }}
        run: |
          # Get code changes and properly escape them
          CODE_CHANGES=$(git diff HEAD^ HEAD | python3 -c '
          import sys, json
          print(json.dumps(sys.stdin.read()))
          ')[1:-1]  # Remove surrounding quotes

          # Create a temporary JSON file for the commit data
          echo '{
            "records": [{
              "fields": {
                "Commit Date": "'$(git log -1 --pretty=format:"%ad" --date=iso)'",
                "Repository URL": "${{ github.server_url }}/${{ github.repository }}",
                "Author Email": "'$(git log -1 --pretty=format:"%ae")'",
                "Repository Name": "${{ github.repository }}",
                "Commit Message": "'$(git log -1 --pretty=format:"%s" | sed 's/"/\\"/g')'",
                "Github Username": "${{ github.actor }}",
                "Code Committed": "'"$CODE_CHANGES"'"
              }
            }]
          }' > commit_data.json

          # Send data to Airtable
          curl -X POST "$AIRTABLE_API_URL" \
            -H "Authorization: Bearer $AIRTABLE_API_KEY" \
            -H "Content-Type: application/json" \
            -d @commit_data.json
